# Generated by Django 6.0.5 on 2026-05-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_med_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
