# Generated by Django 6.0.5 on 2026-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_med_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='time_taken',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
    ]
