# Generated by Django 6.0.5 on 2026-05-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_med_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='taken',
        ),
    ]
